# image: docker/compose:1.25.4

# options:
#   docker: true

pipelines:
  default:
    - step:
        name: Backend Test
        image: php:7.2.27-cli-buster
        script:
          - apt-get update && apt-get install -y \
              libfreetype6-dev \
              libjpeg62-turbo-dev \
              libmcrypt-dev \
              libpng-dev \
              libzip-dev \
              libmagickwand-dev \
              imagemagick \
              libcurl4-openssl-dev \
              && docker-php-ext-configure gd  --with-freetype-dir=/usr --with-jpeg-dir=/usr --with-png-dir=/usr \
              && docker-php-ext-install -j$(nproc) gd \
              && pecl install imagick \
              && docker-php-ext-enable imagick \
              && docker-php-ext-install zip xml intl curl\
              && docker-php-ext-install pdo
          - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && php composer-setup.php && php -r "unlink('composer-setup.php');"
          - php composer.phar --working-dir=./laravel install
          - php composer.phar --working-dir=./laravel pipeline:checks
    # - step:
    #     script:
    #       - docker-compose build app test-runner 
    #       - docker-compose up test-runner
    #       - docker-compose down
    #     services:
    #       - docker