image: docker/compose:1.25.4

options:
  docker: true

pipelines:
  default:
    - step:
        script:
          - docker-compose build app test-runner 
          - docker-compose up test-runner
          - docker-compose down
        services:
          - docker