version: '3'
services:
  front:
    image: node:12.16-slim
    working_dir: "/var/www/app"
    environment:
      - HOST=0.0.0.0
    ports:
      - "${NUXT_PORT}:3000"
    volumes:
      - ./frontend:/var/www/app
    command: bash -c "npm install && npm run dev"
    depends_on:
      - app

  app:
    build:
      context: ./laravel
      dockerfile: ./docker/apache/Dockerfile
      args:
        COMPOSER: "true"
        XDEBUG: "true"
    volumes:
      - './laravel:/var/www/html'
    ports:
      - '${HTTP_PORT}:80'
    environment:
      APP_KEY: base64:Wl8MrDC7UiWbz2+9jowCzp7R+cVqF+ZuVf/vj/uKZ+8=
      DEBUG: "true"
      DB_HOST: mysql
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_PORT: 3306
      MAIL_DRIVER: smtp
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_ENCRYPTION: null
      MAIL_FROM_ADDRESS: no-reply@bunkermaestro.com
      MAIL_FROM_NAME: BunkerMaestro
    depends_on:
      - mysql
      - mailhog

  mysql:
    build:
      context: ./laravel/docker/mysql
      args:
        - 'MYSQL_VERSION=${MYSQL_VERSION}'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - '${DATA_PATH_HOST}/mysql:/var/lib/mysql'
      - '${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d'
    ports:
      - '${MYSQL_PORT}:3306'

  mailhog:
    image: mailhog/mailhog:latest
    environment:
      MH_STORAGE: maildir
    volumes:
      - ${DATA_PATH_HOST}/mailhog:/maildir:rw,delegated
    ports:
        - "${MAILHOG_HTTP_PORT}:8025"
        - "${MAILHOG_MAIL_PORT}:1025"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      PMA_ABSOLUTE_URI: 'localhost:${PMA_PORT}'
    ports:
      - '${PMA_PORT}:80'